### ISSUE TITLE
Python access example not working

### ISSUE THREAD

**Issue by rgommers** [IVFL-BOKU/sentinel2#1]
Hi, not sure if this is the right repo, but it's the only way I can find to send some feedback. The Python example at https://s2.boku.eodc.eu/wiki/#!codeSamples.md is broken (at least on Python 3.5), and it uses ``urllib`` while it should be using ``requests``. Please replace it with this:

    import json
    import requests

    user = 'your_username'
    pwd = 'your_password'

    # find some granules
    req = 'https://s2.boku.eodc.eu/granule?atmCorr=1&geometry={"type":"Point","coordinates":[16.5,48.5]}'
    response = requests.get(req, auth=(user, pwd))
    granules = response.json()
    print(granules)

**Comment by zozlak** [comment]
This is a wrong repo but there is no better place to post your feedback :)

You are right, I tested the current code only against Python 2.7 and it does not work in 3.5.

As the requests module's get/post/etc functions provide a nice way to pass query parameters, I tuned up your code a little bit - see https://s2.boku.eodc.eu/wiki/#!codeSamples.md

The image download code is now far more complicated but will work in both 2.7 and 3.5 and Python fun would say it is more pythonic.

**Comment by rgommers** [comment]
That looks good, thanks @zozlak
